//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public long userID { get; set; }
        public string name { get; set; }
        public string mail { get; set; }
        public int roleID { get; set; }
        public string vk_userID { get; set; }
        public Nullable<System.DateTime> change_on { get; set; }
    }
}
